LTO_ENABLE = yes
COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
LEADER_ENABLE = yes
COMMAND_ENABLE = no    # Deaktiviert die Magic-Befehle (Bootloader-Sprung etc.)
CONSOLE_ENABLE = no    # Deaktiviert Debugging-Output (spart viel Platz!)
MOUSEKEY_ENABLE = no   # Falls du keine Maussteuerung über die Tastatur brauchst
EXTRAKEY_ENABLE = no   # Media-Tasten, Systemsteuerung
MUSIC_ENABLE = no      # Musik-Modus
